# Generated by Django 4.1.5 on 2023-02-07 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cragName', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutsideConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RockConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeOfDay', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('crag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditionsapi.crags')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditionsapi.goals')),
                ('outsideconditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='conditionsapi.outsideconditions')),
                ('rock_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditionsapi.rockconditions')),
                ('time_of_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditionsapi.timeofday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
