# Generated by Django 4.1.5 on 2023-02-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditionsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideconditions',
            name='isGood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rockconditions',
            name='isGood',
            field=models.BooleanField(default=False),
        ),
    ]
